language: python
python:
  - "3.6"
  - "3.7"
env:
  - JOB=test SUITE=unit
  - JOB=test SUITE=system

# - perform pre-commit checks only once
# - perform doc build only on commit to develop or master
jobs:
  include:
  - env: JOB=check
  - env: JOB=deploy
    if: (branch = master OR branch = develop OR branch = ci_script_check) AND type = push

install:
  - ./ci_scripts/install.sh
script:
  - ./ci_scripts/script.sh
after_success:
 - ./ci_scripts/after_success.sh

before_deploy:
 - ./ci_scripts/build_docs.sh
deploy:
  provider: pages
  token: $GITHUB_TOKEN
  edge: true
  keep_history: true
  skip_cleanup: true
  local_dir: docs/build
  on:
    condition: $JOB = deploy
    all_branches: true
