language: python
python:
  - "3.6"
  - "3.7"
env:
  - JOB=TEST SUITE=unit
  - JOB=TEST SUITE=system

# Perform pre-commit checks only once:
jobs:
  include:
  - env: JOB=CHECK

install:
  - ./ci_scripts/install.sh
script:
  - ./ci_scripts/script.sh
after_success:
 - ./ci_scripts/after_success.sh
