Genetic Programming
-------------------

Components
**********

.. automodule:: gama.genetic_programming.components
    :no-members:

Individual
~~~~~~~~~~

.. autoclass:: Individual

Primitive
~~~~~~~~~

.. autoclass:: Primitive

PrimitiveNode
~~~~~~~~~~~~~

.. autoclass:: PrimitiveNode

Terminal
~~~~~~~~

.. autoclass:: Terminal

Mutation
********

.. automodule:: gama.genetic_programming.mutation
    :members:

Crossover
*********

.. automodule:: gama.genetic_programming.crossover
    :members:
