name: Docs

on:
  push:
    branches:
      - master
      - main
      - "[0-9][0-9].[0-9]+.x"

  pull_request:
    branches:
      - master
      - main
      - "[0-9][0-9].[0-9]+.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[doc]"

      - name: Clone GH-Pages
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v3
        with:
          ref: "gh-pages"
          path: docs/build/

      - name: Build Docs
        run: |
          sphinx-build docs/source docs/build/${{ github.ref_name }}

      - name: Push GH-Pages
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cd docs/build
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ${{ github.ref_name }}
          git commit -m "Autodeploy docs"
          git push
