name: pytest
on:
  workflow_dispatch:
  pull_request:

jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Invoke Unit Tests
        uses: ./.github/actions/pytest
        with:
          path: tests/unit
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}

  system:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Invoke System Tests
        uses: ./.github/actions/pytest
        with:
          path: tests/system
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}
