name: Test --pre
on:
  workflow_dispatch:
  schedule:
    - cron: "00 0 * * 1"

jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Invoke Unit Tests
        uses: ./.github/actions/pytest
        with:
          path: tests/unit
          python-version: ${{ matrix.python-version }}
          use-cache: false
          pip-args: "--pre"
          pytest-args: "-W error -W ignore::sklearn.exceptions.ConvergenceWarning"
